typography_spectrum: 0.6596203458029777
color:
  saturation: 0.34391369158402085
  brandStrength: 0.9536467860452831
  rhythmicContrast: 0.6679772243369371
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  lightness: 0.37916453112848103
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8746820029336959
analytics:
  twitter: null
  google: UA-17071199-1
  facebook: null
name: Eight Corners
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - id: 'http://eightcorners.co'
    url: 'http://eightcorners.co'
    name: Home
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Eight Corners
purpose: []
