name: Eight Corners
favicon: null
layout_spectrum: 0.74684
typography_spectrum: 0.37616
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Eight Corners
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-17071199-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#3f3f3f'
  brandStrength: 0.1875
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
