name: Eight Corners Blog
favicon: null
layout_spectrum: 1
typography_spectrum: 0.75024
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'Eight Corners Blog on Travel, Design, Life.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#212121'
    - '#000000'
    - '#773388'
    - '#f0f0f0'
    - '#ffffff'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.9375
  rhythmicContrast: 0.25
purpose: []
