name: eightcorners
favicon: null
layout_spectrum: 1
typography_spectrum: 0.83723
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7e2781'
    - '#000000'
    - '#800080'
    - '#550055'
    - '#711c71'
  brandStrength: 0.6875
  lightness: 1
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
