typography_spectrum: 0.3660985988099128
color:
  saturation: 0.34391369158402085
  brandStrength: 0.9536467860452831
  rhythmicContrast: 0.6679772243369371
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  lightness: 0.37916453112848103
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4830248453654349
analytics:
  twitter: null
  google: UA-17071199-1
  facebook: '999007766816091'
name: Eight Corners
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: Home
    url: 'http://eightcorners.co'
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Eight Corners
content: []
description: 'Designer, traveller, flat white fanatic.'
purpose:
  - type: external
    url: 'http://eightcorners.co'
    label: Home
  - type: external
    url: 'https://paperform.co/form/appealing-brand'
    label: 8 Simple Steps To Designing An Appealing Brand
