name: Eight Corners Blog
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5066
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'Eight Corners Blog on Travel, Design, Life.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1f1e1d'
    - '#c045ce'
    - '#868686'
    - '#dc9ae3'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.9375
  rhythmicContrast: 1
purpose: []
