name: Eight Corners
favicon: null
layout_spectrum: 0.50179
typography_spectrum: 0.37616
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Eight Corners
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-17071199-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#783489'
    - '#000000'
    - '#afafaf'
    - '#7f7f7f'
  brandStrength: 0.25
  lightness: 1
  saturation: 0.875
  rhythmicContrast: 1
purpose: []
