name: Eight Corners
favicon: null
layout_spectrum: 1
typography_spectrum: 0.85384
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Eight Corners
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-17071199-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#212121'
    - '#000000'
    - '#773388'
    - '#f0f0f0'
    - '#ffffff'
  brandStrength: 0
  lightness: 1
  saturation: 0.875
  rhythmicContrast: 1
purpose: []
